// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/logtest/logtest.proto

package ps_clientele_svc_logtest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Logtest service

type LogtestService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Logtest_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Logtest_PingPongService, error)
}

type logtestService struct {
	c    client.Client
	name string
}

func NewLogtestService(name string, c client.Client) LogtestService {
	return &logtestService{
		c:    c,
		name: name,
	}
}

func (c *logtestService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Logtest.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logtestService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Logtest_StreamService, error) {
	req := c.c.NewRequest(c.name, "Logtest.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &logtestServiceStream{stream}, nil
}

type Logtest_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type logtestServiceStream struct {
	stream client.Stream
}

func (x *logtestServiceStream) Close() error {
	return x.stream.Close()
}

func (x *logtestServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *logtestServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logtestServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logtestServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logtestService) PingPong(ctx context.Context, opts ...client.CallOption) (Logtest_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Logtest.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &logtestServicePingPong{stream}, nil
}

type Logtest_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type logtestServicePingPong struct {
	stream client.Stream
}

func (x *logtestServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *logtestServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *logtestServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logtestServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logtestServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *logtestServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Logtest service

type LogtestHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Logtest_StreamStream) error
	PingPong(context.Context, Logtest_PingPongStream) error
}

func RegisterLogtestHandler(s server.Server, hdlr LogtestHandler, opts ...server.HandlerOption) error {
	type logtest interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Logtest struct {
		logtest
	}
	h := &logtestHandler{hdlr}
	return s.Handle(s.NewHandler(&Logtest{h}, opts...))
}

type logtestHandler struct {
	LogtestHandler
}

func (h *logtestHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.LogtestHandler.Call(ctx, in, out)
}

func (h *logtestHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.LogtestHandler.Stream(ctx, m, &logtestStreamStream{stream})
}

type Logtest_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type logtestStreamStream struct {
	stream server.Stream
}

func (x *logtestStreamStream) Close() error {
	return x.stream.Close()
}

func (x *logtestStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *logtestStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logtestStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logtestStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *logtestHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.LogtestHandler.PingPong(ctx, &logtestPingPongStream{stream})
}

type Logtest_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type logtestPingPongStream struct {
	stream server.Stream
}

func (x *logtestPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *logtestPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *logtestPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *logtestPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *logtestPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *logtestPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
